version: "2.1"
services:
    limesurvey:
        build: .
        container_name: limesurvey
        ports:
            - 5000:80
        volumes:
            - ./LimeSurvey:/var/www/html/
        depends_on:
            - limesurvey_db
        networks:
            net: 
                ipv4_address: 10.5.0.5
    limesurvey_db:
        image: mysql:5.5.61
        container_name: limesurvey_db
        command: --init-file /data/application/init.sql
        restart: always
        networks:
            net: 
                ipv4_address: 10.5.0.6
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data:/var/lib/mysql
            - ./sql/create_tables.sql:/data/application/init.sql
    react:
        build: ./react-app
        container_name: react
        environment:
            - NODE_ENV=production
        command: npm start
        ports:
            - 80:3000
        volumes:
            - ./react-app:/app
        networks:
            net: 
                ipv4_address: 10.5.0.7
    flask:
        build:
            context: ./flask
        container_name: flask
        ports:
            - 8080:8080
        networks:
            net: 
                ipv4_address: 10.5.0.8
networks:
    net:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1
